### ISSUE TITLE
Doesn't work if tmux isn't already running

### ISSUE THREAD

**Issue by mxmilkiib** [lf94/peek-for-tmux#2]
`error connecting to /tmp/tmux-1000/default (No such file or directory)`

**Comment by lf94** [comment]
It relies on tmux, so it makes sense it will not work if it isn't running.

I would rather not add a check to see if it is not running, then start it. I want to keep the line as simple as possible.

**Comment by mxmilkiib** [comment]
I wouldn't say it's simple if it requires tmux to be running, because that's a step left for the user which makes it more complex for them. That's not to say I'm right but to note that saying "simple" is subjective, but ultimately it's your call how you wish this snippet to perform. (I'm using a tiling window manager so don't need tmux running most of the time, though would prefer an in-window view, albeit with `bat` not $EDITOR, as it's quicker than launching a new terminal window.)
