### ISSUE TITLE
What the meaning of `|| exit;` here?

### ISSUE THREAD

**Issue by laixintao** [lf94/peek-for-tmux#4]
I delete this, just use 

```
peek() { tmux split-window -p 33 "$EDITOR" "$@" }
```

It also works, can anybody explain why? 

Thanks!

**Comment by lf94** [comment]
The `|| exit` was because quitting the editor did not close the window for me for some reason...But this is when I was using `&& exit`. I can't remember if I tried without.

**Comment by lf94** [comment]
It appears though it works with `|| exit` as you say. Cool! :) I will updated this.

**Comment by laixintao** [comment]
Cool.
